server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    expires -1;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Permissions-Policy "camera=(self)" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
